modLoader="javafml"
loaderVersion="[43,)"
license = "All Rights Reserved"

[[mods]]
modId="thirteen_flames"
version="${file.jarVersion}"
displayName="Storytelling: Thirteen Flames"
logoFile="logo.png"
credits="MrLololoshka, Storytelling Team"
authors="xXinailXx"
description='''Mod adds most of the items and mechanics from Lp.Тринадцать Огней'''

[[dependencies.thirteen_flames]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.thirteen_flames]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.thirteen_flames]]
modId="enderdragonlib"
mandatory=true
versionRange="[0.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.thirteen_flames]]
modId="alexsmobs"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.thirteen_flames]]
modId="citadel"
mandatory=true
versionRange="[2.1.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.thirteen_flames]]
modId="hammerlib"
mandatory=true
versionRange="[19.3.57,)"
ordering="NONE"
side="BOTH"
[[dependencies.thirteen_flames]]
modId="relics"
mandatory=true
versionRange="[0.4.7.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.thirteen_flames]]
modId="geckolib3"
mandatory=true
versionRange="[3.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.thirteen_flames]]
modId = "curios"
mandatory = true
versionRange = "[1.19.2-5.1.1.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.thirteen_flames]]
modId = "skilltree"
mandatory = true
versionRange = "[0.4.9e,)"
ordering = "NONE"
side = "BOTH"
